# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [2]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [4]:
chipo.shape

(4622, 5)

# Name of the max valued product

In [5]:
chipo["item_price"] = chipo["item_price"].str.replace("$", "").astype(float)

In [6]:
chipo[["item_price", "item_name"]].sort_values(by="item_price", ascending=False).head(1)

      item_price                     item_name
3598       44.25  Chips and Fresh Tomato Salsa

### Step 4. How many products cost more than $10.00?

In [7]:
chipo[chipo["item_price"] > 10].describe()

          order_id     quantity   item_price
count  1130.000000  1130.000000  1130.000000
mean    944.354867     1.162832    12.392513
std     527.023314     0.682593     3.199968
min       2.000000     1.000000    10.500000
25%     498.000000     1.000000    11.250000
50%     957.500000     1.000000    11.250000
75%    1410.750000     1.000000    11.750000
max    1834.000000    15.000000    44.250000

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [8]:
chipo[["item_name", "item_price"]].value_counts()

item_name            item_price
Chips and Guacamole  4.45          349
Chicken Bowl         8.75          313
Canned Soft Drink    1.25          264
Chicken Burrito      8.75          230
Chicken Bowl         11.25         228
                                  ...
Chips and Guacamole  8.50            1
Steak Soft Tacos     18.50           1
Chips and Guacamole  17.80           1
Chips                1.99            1
Barbacoa Bowl        11.49           1
Name: count, Length: 209, dtype: int64

### Step 6. Sort by the name of the item

In [9]:
chipo["item_name"].sort_values()

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
              ...
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, Length: 4622, dtype: str

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

V1

In [10]:
chipo[["quantity", "item_price"]].sort_values(by="item_price", ascending= False).head(1)

      quantity  item_price
3598        15       44.25

V2

In [17]:
chipo[["quantity", "item_price"]].max().to_frame()

                0
quantity    15.00
item_price  44.25

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [22]:
len(chipo[chipo["item_name"] == "Veggie Salad Bowl"])

18

### Step 9. How many times did someone order more than one Canned Soda?

In [38]:
chipo[[chipo["item_name"] == "Canned Soda"] and chipo["quantity"] > 1]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
18,9,2,Canned Soda,[Sprite],2.18
51,23,2,Canned Soda,[Mountain Dew],2.18
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",22.50
148,67,2,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...",17.98
...,...,...,...,...,...
4491,1786,4,Canned Soft Drink,[Sprite],5.00
4499,1789,2,Canned Soft Drink,[Coke],2.50
4560,1812,2,Canned Soft Drink,[Coke],2.50
4561,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",17.50
4582,1822,2,Bottled Water,NaN,3.00