# Web Scraping con Selenium

##### Extrae de las películas en cartelera datos. De ellas vamos a extraer la siguiente información:
- ##### Fecha de estreno
- ##### URL
- ##### Datos principales, como hemos hecho al principio
- ##### Nota media
- ##### Cantidad de votos
- ##### Críticas profesionales buenas, regulares y malas
- ##### Cinco primeras críticas

Importación de las librerías

In [64]:
# Para la manipulación de datos
import pandas as pd

# Servicio y driver de Chrome de Selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# Las opciones que vamos a tener para buscar elementos
from selenium.webdriver.common.by import By

# Para cuando queramos mandar pulsaciones de teclado
from selenium.webdriver.common.keys import Keys

# Hacemos que espere
import time

# Importaciones para esperas explícitas (mejor práctica que time.sleep)
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Importamos undetected-chromedriver para evitar el captcha
import undetected_chromedriver as uc

# Importamos excepciones comunes de Selenium para manejo de errores
from selenium.common.exceptions import NoSuchElementException, TimeoutException, ElementClickInterceptedException

In [65]:
service = Service(ChromeDriverManager().install())

In [66]:
from selenium import webdriver

driver = webdriver.Chrome()
print(driver.capabilities["browserVersion"])
driver.quit()

146.0.7680.154

Creamos el driver para controlar el navegador

In [67]:
import undetected_chromedriver as uc

driver = uc.Chrome(
    browser_executable_path=r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    service=service,
    use_subprocess=False,
    headless=False,
)

RECUERDA:

##### Beginner Selenium Cheatsheet:
Sacar un elemento:
- element = driver.find_element(by, value)

Sacar varios elementos:
- element = driver.find_elements(by, value)

Sacar atributos:
- attribute = element.--el atributo--
- attribute = element.get_attribute(--el atributo--)

Hacer click:
- element.click()

Teclear:
- element.send_keys()

Gestión de pestañas:
- driver.switch_to.window(driver.window_handles[-1])
- driver.get(url)
- driver.close()

Accedemos a la página principal

In [68]:
url = "https://www.filmaffinity.com"
driver.get(url)

Aceptamos el pop-up de ser necesario

In [69]:
# tu código
element_by_tag = driver.find_elements(By.TAG_NAME, "button")
print(element_by_tag)

time.sleep(1)
accept = driver.find_element(By.ID, "accept-btn").click()
time.sleep(1)

cartelera = driver.find_element(By.LINK_TEXT, "Películas en cartelera")
cartelera.click()

[<undetected_chromedriver.webelement.WebElement (session="b5db6d51ea42cfffcf8c955246dcf636", element="f.C98EBAB8F84E495FBBDE745AF0966838.d.1693C977A2B76248F73372BBA0D6AB60.e.145")>, <undetected_chromedriver.webelement.WebElement (session="b5db6d51ea42cfffcf8c955246dcf636", element="f.C98EBAB8F84E495FBBDE745AF0966838.d.1693C977A2B76248F73372BBA0D6AB60.e.146")>]

Hacemos una función que devuelva en un diccionario todos los datos de las películas, salvo la fecha de estreno y la url

Parámetros: url y fecha de estreno
Salida: Diccionario con todos los datos

In [70]:
# wait = WebDriverWait(driver, 5)
# wait.until(EC.presence_of_element_located((By.CLASS_NAME, "movie-title")))
# movie_links = driver.find_elements(By.CLASS_NAME, "movie-title")

# print(f"Elementos encontrados: {len(movie_links)}")

# for i, elem in enumerate(movie_links):
#     print(f"[{i}] Tag: {elem.tag_name} | Texto: {elem.text} | href: {elem.get_attribute('href')}")

In [71]:
def get_datos_pelicula(driver, url, estreno):
    all_movies = {}

    all_movies["fecha_estreno"] = estreno
    all_movies["url"] = url

    driver.get(url)
    time.sleep(2)

    # Datos principales
    data = driver.find_element(By.CLASS_NAME, "movie-info")
    dts = data.find_elements(By.TAG_NAME, "dt")
    dds = data.find_elements(By.TAG_NAME, "dd")

    # Añado los dts y dds en el diccionario
    for x, y in zip(dts, dds):
        all_movies[x.text.strip()] = y.text.strip()

    nota_media = driver.find_elements(By.ID, value="movie-rat-avg")
    if len(nota_media) > 0:
        all_movies["nota_media"] = nota_media[0].text

    cantidad_votos = driver.find_elements(By.CSS_SELECTOR, value="#movie-count-rat span")
    if len(cantidad_votos) > 0:
        all_movies["cantidad_votos"] = cantidad_votos[0].text

    n_criticas = driver.find_elements(By.CSS_SELECTOR, value="#right-column > a > div > div.body > div > div.legend-wrapper .leg")

    if len(n_criticas) > 0:
        positivas = n_criticas[0].text
        all_movies["positivas"] = positivas

        regulares = n_criticas[1].text
        all_movies["regulares"] = regulares

        negativas = n_criticas[2].text
        all_movies["negativas"] = negativas

    criticas = driver.find_elements(By.CSS_SELECTOR, value="ul#pro-reviews li")
    i = 0

    while i < 5 and i < len(criticas):
        critica = criticas[i].find_element(by=By.CSS_SELECTOR, value='div div').text
        all_movies['critica_'+str(i)] = critica

        i += 1

    return all_movies

In [72]:
# prueba = get_datos_pelicula(driver, "https://www.filmaffinity.com/es/film618375.html", "fecha")
# prueba
# all_movies = []

# Sacamos las fechas de estreno dentro de cartelera
# fecha_estreno = driver.find_elements(By.CLASS_NAME, "release-text")

# Sacamos los links de acceso a todas las peliculas de cartelera
movie_link = driver.find_elements(by=By.CSS_SELECTOR, value='div.col a.poster-wrap')

# Creamos una lista vacía a la que le añadimos los links
hrefs = []

for elemento in movie_link:

    estreno = elemento.find_element(by=By.CSS_SELECTOR, value='small.release-text').text
    link_pelicula = {
            'título': elemento.get_attribute('title'),
            'url': elemento.get_attribute('href'),
            'estreno': estreno.replace("\n", " ")
    }

    hrefs.append(link_pelicula)

print(f"Links guardados: {len(hrefs)}")

# iteramos la lista de links para acceder a cada una y aplicar la funcion definida previamente
df = None
for href in hrefs:
    datos_pelicula = get_datos_pelicula(driver, href["url"], href["estreno"])
    print(f"Navegando a: {href}")

    if df is None:
        df = pd.DataFrame(columns=datos_pelicula.keys())
    
    df = pd.concat([df, pd.DataFrame(datos_pelicula, index = [0])], ignore_index=True)
    print(f"Añadida {datos_pelicula['Título original']}")

#     data = driver.find_element(By.CLASS_NAME, "movie-info")
#     dts = data.find_elements(By.TAG_NAME, "dt")
#     dds = data.find_elements(By.TAG_NAME, "dd")

#     pelicula = {}
#     for x, y in zip(dts, dds):
#         pelicula[x.text.strip()] = y.text.strip()

#     all_movies.append(pelicula)

#     driver.back()
#     wait.until(EC.presence_of_element_located((By.CLASS_NAME, "movie-title")))

# print(all_movies)

Links guardados: 60
Navegando a: {'título': 'Amarga Navidad ', 'url': 'https://www.filmaffinity.com/es/film310439.html', 'estreno': '20 mar.'}
Añadida Amarga Navidad
Navegando a: {'título': 'Whistle: El silbido del mal ', 'url': 'https://www.filmaffinity.com/es/film261988.html', 'estreno': '20 mar.'}
Añadida Whistle
Navegando a: {'título': 'Una hija en Tokio ', 'url': 'https://www.filmaffinity.com/es/film691891.html', 'estreno': '20 mar.'}
Añadida Une part manquanteaka
Navegando a: {'título': 'Elegir mi vida ', 'url': 'https://www.filmaffinity.com/es/film913052.html', 'estreno': '20 mar.'}
Añadida Partir un jouraka
Navegando a: {'título': 'Tafiti y sus amigos ', 'url': 'https://www.filmaffinity.com/es/film448750.html', 'estreno': '20 mar.'}
Añadida Tafiti - Ab durch die Wüste
Navegando a: {'título': 'Your Name. ', 'url': 'https://www.filmaffinity.com/es/film307521.html', 'estreno': '20 mar.'}
Añadida Kimi no Na wa. (Your Name.)
Navegando a: {'título': 'La sonrisa del mal ', 'url': 'https://www.filmaffinity.com/es/film359278.html', 'estreno': '20 mar.'}
Añadida La valle dei sorrisi
Navegando a: {'título': 'Nos veremos esta noche, mi amor ', 'url': 'https://www.filmaffinity.com/es/film718849.html', 'estreno': '20 mar.'}
Añadida Nos veremos esta noche, mi amor
Navegando a: {'título': 'Dhurandhar: The Revenge ', 'url': 'https://www.filmaffinity.com/es/film343952.html', 'estreno': '19 mar.'}
Añadida Dhurandhar: The Revengeaka
Navegando a: {'título': 'Torrente presidente ', 'url': 'https://www.filmaffinity.com/es/film453739.html', 'estreno': '13 mar.'}
Añadida Torrente presidenteaka
Navegando a: {'título': 'Águilas de El Cairo ', 'url': 'https://www.filmaffinity.com/es/film314137.html', 'estreno': '13 mar.'}
Añadida Eagles of the Republicaka
Navegando a: {'título': 'El testamento de Ann Lee ', 'url': 'https://www.filmaffinity.com/es/film842010.html', 'estreno': '13 mar.'}
Añadida The Testament of Ann Lee
Navegando a: {'título': 'El arquitecto ', 'url': 'https://www.filmaffinity.com/es/film855002.html', 'estreno': '13 mar.'}
Añadida L'inconnu de la Grande Archeaka
Navegando a: {'título': 'No te queda otra ', 'url': 'https://www.filmaffinity.com/es/film732131.html', 'estreno': '13 mar.'}
Añadida Aimons-nous vivants
Navegando a: {'título': 'La hija pequeña ', 'url': 'https://www.filmaffinity.com/es/film781408.html', 'estreno': '13 mar.'}
Añadida La petite dernière
Navegando a: {'título': 'Las locas del obelisco ', 'url': 'https://www.filmaffinity.com/es/film310301.html', 'estreno': '13 mar.'}
Añadida Las locas del obelisco
Navegando a: {'título': '¡La novia! ', 'url': 'https://www.filmaffinity.com/es/film316105.html', 'estreno': '6 mar.'}
Añadida The Bride!
Navegando a: {'título': 'Hoppers ', 'url': 'https://www.filmaffinity.com/es/film150426.html', 'estreno': '6 mar.'}
Añadida Hoppers
Navegando a: {'título': 'El mago del Kremlin ', 'url': 'https://www.filmaffinity.com/es/film923268.html', 'estreno': '6 mar.'}
Añadida Le Mage du Kremlinaka
Navegando a: {'título': 'El último vikingo ', 'url': 'https://www.filmaffinity.com/es/film295464.html', 'estreno': '6 mar.'}
Añadida Den Sidste Vikingaka
Navegando a: {'título': 'Cleaner: Rescate vertical ', 'url': 'https://www.filmaffinity.com/es/film285634.html', 'estreno': '6 mar.'}
Añadida Cleaner
Navegando a: {'título': 'Línea de extinción ', 'url': 'https://www.filmaffinity.com/es/film324038.html', 'estreno': '6 mar.'}
Añadida Elevation
Navegando a: {'título': 'Caminando con el diablo ', 'url': 'https://www.filmaffinity.com/es/film190955.html', 'estreno': '6 mar.'}
Añadida Caminando con el diablo
Navegando a: {'título': 'Pillion ', 'url': 'https://www.filmaffinity.com/es/film363348.html', 'estreno': '6 mar.'}
Añadida Pillion
Navegando a: {'título': 'El rostro del perdón ', 'url': 'https://www.filmaffinity.com/es/film633097.html', 'estreno': '6 mar.'}
Añadida The Face of the Faceless
Navegando a: {'título': 'La sombra de mi padre ', 'url': 'https://www.filmaffinity.com/es/film124261.html', 'estreno': '6 mar.'}
Añadida My Father's Shadow
Navegando a: {'título': 'Caravan ', 'url': 'https://www.filmaffinity.com/es/film703556.html', 'estreno': '6 mar.'}
Añadida Karavanaka
Navegando a: {'título': 'Scream 7 ', 'url': 'https://www.filmaffinity.com/es/film675046.html', 'estreno': '27 feb.'}
Añadida Scream 7
Navegando a: {'título': 'Los miserables. El origen ', 'url': 'https://www.filmaffinity.com/es/film403747.html', 'estreno': '27 feb.'}
Añadida Jean Valjeanaka
Navegando a: {'título': 'Sorry, Baby ', 'url': 'https://www.filmaffinity.com/es/film520114.html', 'estreno': '27 feb.'}
Añadida Sorry, Baby
Navegando a: {'título': 'EPiC: Elvis Presley in Concert ', 'url': 'https://www.filmaffinity.com/es/film630582.html', 'estreno': '27 feb.'}
Añadida EPiC: Elvis Presley in Concert
Navegando a: {'título': 'Orwell: 2+2=5 ', 'url': 'https://www.filmaffinity.com/es/film327123.html', 'estreno': '27 feb.'}
Añadida Orwell: 2+2=5
Navegando a: {'título': 'Greenland 2 ', 'url': 'https://www.filmaffinity.com/es/film853860.html', 'estreno': '20 feb.'}
Añadida Greenland 2: Migration
Navegando a: {'título': 'El agente secreto ', 'url': 'https://www.filmaffinity.com/es/film457500.html', 'estreno': '20 feb.'}
Añadida O Agente Secretoaka
Navegando a: {'título': 'La maldición de Shelby Oaks ', 'url': 'https://www.filmaffinity.com/es/film870836.html', 'estreno': '20 feb.'}
Añadida Shelby Oaks
Navegando a: {'título': 'Little Amélie ', 'url': 'https://www.filmaffinity.com/es/film210175.html', 'estreno': '20 feb.'}
Añadida Amélie et la Métaphysique des tubesaka
Navegando a: {'título': 'Balandrau, viento salvaje ', 'url': 'https://www.filmaffinity.com/es/film134886.html', 'estreno': '20 feb.'}
Añadida Balandrau, vent salvatge
Navegando a: {'título': 'Las líneas discontinuas ', 'url': 'https://www.filmaffinity.com/es/film409255.html', 'estreno': '20 feb.'}
Añadida As liñas descontinuas
Navegando a: {'título': 'Cumbres borrascosas ', 'url': 'https://www.filmaffinity.com/es/film608251.html', 'estreno': '13 feb.'}
Añadida Wuthering Heightsaka
Navegando a: {'título': 'Como cabras ', 'url': 'https://www.filmaffinity.com/es/film967461.html', 'estreno': '13 feb.'}
Añadida GOAT
Navegando a: {'título': 'Ruta de escape ', 'url': 'https://www.filmaffinity.com/es/film960118.html', 'estreno': '13 feb.'}
Añadida Crime 101
Navegando a: {'título': 'No hay otra opción ', 'url': 'https://www.filmaffinity.com/es/film288774.html', 'estreno': '13 feb.'}
Añadida No Other Choiceaka
Navegando a: {'título': 'La fiera ', 'url': 'https://www.filmaffinity.com/es/film571051.html', 'estreno': '6 feb.'}
Añadida La fiera
Navegando a: {'título': 'Tres adioses ', 'url': 'https://www.filmaffinity.com/es/film580752.html', 'estreno': '6 feb.'}
Añadida Tre ciotole
Navegando a: {'título': 'Evolution ', 'url': 'https://www.filmaffinity.com/es/film872994.html', 'estreno': '6 feb.'}
Añadida Evolution
Navegando a: {'título': 'La tarta del presidente ', 'url': 'https://www.filmaffinity.com/es/film888907.html', 'estreno': '6 feb.'}
Añadida Mamlaket Al-Qasabaka
Navegando a: {'título': 'Marty Supreme ', 'url': 'https://www.filmaffinity.com/es/film380589.html', 'estreno': '30 ene.'}
Añadida Marty Supremeaka
Navegando a: {'título': 'Aída y vuelta ', 'url': 'https://www.filmaffinity.com/es/film186074.html', 'estreno': '30 ene.'}
Añadida Aída y vuelta
Navegando a: {'título': 'La chica zurda ', 'url': 'https://www.filmaffinity.com/es/film730574.html', 'estreno': '30 ene.'}
Añadida Left-Handed Girl
Navegando a: {'título': 'Hamnet ', 'url': 'https://www.filmaffinity.com/es/film868058.html', 'estreno': '23 ene.'}
Añadida Hamnet
Navegando a: {'título': 'La asistenta ', 'url': 'https://www.filmaffinity.com/es/film530880.html', 'estreno': '1 ene.'}
Añadida The Housemaid
Navegando a: {'título': 'Rondallas ', 'url': 'https://www.filmaffinity.com/es/film683814.html', 'estreno': '1 ene.'}
Añadida Rondallas
Navegando a: {'título': 'Abuela tremenda ', 'url': 'https://www.filmaffinity.com/es/film515832.html', 'estreno': '1 ene.'}
Añadida Abuela tremenda
Navegando a: {'título': 'Avatar: Fuego y ceniza ', 'url': 'https://www.filmaffinity.com/es/film191071.html', 'estreno': '19 dic.'}
Añadida Avatar: Fire and Ash
Navegando a: {'título': 'Valor sentimental ', 'url': 'https://www.filmaffinity.com/es/film901036.html', 'estreno': '5 dic.'}
Añadida Sentimental Valueaka
Navegando a: {'título': 'Zootrópolis 2 ', 'url': 'https://www.filmaffinity.com/es/film269061.html', 'estreno': '28 nov.'}
Añadida Zootopia 2
Navegando a: {'título': 'Los domingos ', 'url': 'https://www.filmaffinity.com/es/film584300.html', 'estreno': '24 oct.'}
Añadida Los domingos
Navegando a: {'título': 'Sirât ', 'url': 'https://www.filmaffinity.com/es/film780154.html', 'estreno': '6 jun.'}
Añadida Sirât
Navegando a: {'título': 'Los pecadores ', 'url': 'https://www.filmaffinity.com/es/film699169.html', 'estreno': '16 abr.'}
Añadida Sinners
Navegando a: {'título': 'Una batalla tras otra ', 'url': 'https://www.filmaffinity.com/es/film910030.html', 'estreno': '26 sept.'}
Añadida One Battle After Another

In [73]:
df

,fecha_estreno,url,Título original,Año,Duración,País,Dirección,Guion,Reparto,Música,...,Sinopsis,nota_media,cantidad_votos,critica_0,critica_1,critica_2,critica_3,critica_4,,Grupos
0,20 mar.,https://www.filmaffinity.com/es/film310439.html,Amarga Navidad,2026,111 min.,España,Pedro Almodóvar,Pedro Almodóvar,Bárbara Lennie\nLeonardo Sbaraglia\nAitana Sán...,Alberto Iglesias. Canción: Amaia,...,Elsa es una directora de publicidad cuya madre...,"6,2",1.685,"""Feliz choque inesperado: Almodóvar lanza su v...","""Almodóvar y las razones, que son emociones, d...","""Almodóvar se encomienda a la autoficción en u...","""Un melodrama preciso y sereno (...) fluye a t...","""Almodóvar pone en imágenes un guion modélico,...",NaN,NaN
1,20 mar.,https://www.filmaffinity.com/es/film261988.html,Whistle,2025,100 min.,Canadá,Corin Hardy,Owen Egerton,Dafne Keen\nSophie Nélisse\nNick Frost\nPercy ...,Doomphonic,...,Un grupo de estudiantes inadaptados encuentra ...,"4,7",370,"""La originalidad no es lo que busca “Whistle”,...","""No sorprende tanto por lo que cuenta como por...","""La trivialidad del desarrollo narrativo, no o...","""Visibiliza la solvencia del director (...) en...","""Whistle cumple las expectativas ofreciendo un...",NaN,NaN
2,20 mar.,https://www.filmaffinity.com/es/film691891.html,Une part manquanteaka,2024,98 min.,Francia,Guillaume Senez,"Guillaume Senez, Jean Denizot",Romain Duris\nJudith Chemla\nMei Cirne-Masuki\...,Olivier Marguerit,...,"Todos los días, Jay conduce su taxi por Tokio ...","6,9",232,"""La película da pocas explicaciones en general...","""Con tacto, la pareja Senez-Duris acierta a co...","""Logra maximizar el impacto emocional de sus m...","""Una cinta delicada y bien escrita (...) Lo me...","""Un filme delicado y conmovedor. De sobriedad ...",,NaN
3,20 mar.,https://www.filmaffinity.com/es/film913052.html,Partir un jouraka,2025,94 min.,Francia,Amélie Bonnin,"Amélie Bonnin, Dimitri Lucas",Juliette Armanet\nBastien Bouillon\nFrançois R...,"Keren Ann, Gonzales, Germain Izydorczyk, Theo ...",...,Cécile está a punto de cumplir su sueño de abr...,"5,9",83,"""Bonnin convierte la nostalgia en el argumento...","""Como película, es de esas que no molestan, qu...","""Una oda a la cultura pop francesa pasada por ...","""Es agradable de ver por el carisma de los act...","""Ni los toques de originalidad del filme nos d...",,NaN
4,20 mar.,https://www.filmaffinity.com/es/film448750.html,Tafiti - Ab durch die Wüste,2025,81 min.,Alemania,"Nina Wels, Timo Berg","Julia Boehme, Nicholas Hause",Cosima Henman\nVoz\nSteve Hudson\nVoz\nDela Da...,Carsten Rocker,...,"Cuando Tafiti, una joven suricata, conoce a Br...",NaN,NaN,"""Son adorables, pero este dúo de suricato y ce...",NaN,NaN,NaN,NaN,NaN,NaN
5,20 mar.,https://www.filmaffinity.com/es/film307521.html,Kimi no Na wa. (Your Name.),2016,106 min.,Japón,Makoto Shinkai,Makoto Shinkai,Animación,Radwimps,...,Taki y Mitsuha descubren un día que durante el...,"7,8",29.580,"""Your Name"" fue un éxito rotundo en taquilla, ...","""Tanto el luminoso estilo del animador como su...","""La película, profundamente adulta y absolutam...","""Fastuoso relato entre realista y fantástico (...","""Your Name es la obra maestra de Makoto Shinka...",NaN,NaN
6,20 mar.,https://www.filmaffinity.com/es/film359278.html,La valle dei sorrisi,2025,122 min.,Italia,Paolo Strippoli,"Jacopo Del Giudice, Paolo Strippoli, Milo Tissone",Michele Riondino\nGiulio Feltri\nPaolo Pierobo...,"Federico Bisozzi, Davide Tomat",...,Remis es un pequeño pueblo enclavado en un val...,"6,5",169,"""Una escalofriante cinta sobre el fanatismo, e...","""Es deliberadamente confusa en buena parte de ...","""Es un híbrido de terror intelectual, sin sust...","""Una sorprendente resurrección del cine de ter...","""Una pesadilla implacable y gráfica (...) 'La ...",NaN,NaN
7,20 mar.,https://www.filmaffinity.com/es/film718849.html,"Nos veremos esta noche, mi amor",2026,79 min.,México,Francisco Arasanz,Francisco Arasanz,"Sergio María, María Monroy, Pao Soppe, Frank R...",NaN,...,"Por un lado, un hombre (Sergio María) queda at...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,19 mar.,https://www.filmaffinity.com/es/film343952.html,Dhurandhar: The Revengeaka,2026,210 min.,India,Aditya Dhar,Aditya Dhar,Ranveer Singh\nSanjay Dutt\nAkshaye Khanna\nMa...,Shashwat Sachdev,...,"Bajo la identidad de Hamza Ali Mazari, el espí...",NaN,NaN,"""Aunque cabe esperar más entregas de este univ...","""La secuela del mayor éxito de Bollywood es má...","""Es una película muy de su tiempo, lo cual no ...",NaN,NaN,,NaN
9,13 mar.,https://www.filmaffinity.com/es/film453739.html,Torrente presidenteaka,2026,102 min.,España,Santiago Segura,Santiago Segura,Santiago Segura\nGabino Diego\nRamón Langa\nCa...,Roque Baños. Canción: Taburete,...,"José Luis Torrente, siempre convencido de ser ...","5,7",4.594,"""Una sátira tan ocurrente y divertida como opo...","""Soez, excesiva y por momentos muy divertida. ...","""Cuñadismo para todos los públicos (...) No ha...","""Una comedia facilona (...) sin tanto colmillo...","""La historia es lo de siempre, pero mucho más ...",,Torrente
10,13 mar.,https://www.filmaffinity.com/es/film314137.html,Eagles of the Republicaka,2025,127 min.,Suecia,Tarik Saleh,Tarik Saleh,Fares Fares\nLyna Khoudri\nZineb Triki\nAmr Wa...,Alexandre Desplat,...,George Fahmy (Fares Fares) el actor más querid...,"6,4",216,"""Cierra la trilogía de Tarik Saleh sobre la ci...","""En su núcleo central deambula un tanto entre ...","""De sus imágenes emerge un duro retrato crític...","""El argumento que trata es interesante, tiene ...","""Se ve lastrada por la tosquedad como narrador...",,Trilogía de El Cairo
11,13 mar.,https://www.filmaffinity.com/es/film842010.html,The Testament of Ann Lee,2025,136 min.,Reino Unido,Mona Fastvold,"Mona Fastvold, Brady Corbet",Amanda Seyfried\nThomasin McKenzie\nLewis Pull...,Daniel Blumberg,...,"Inspirada en hechos reales, se centra en la lí...","5,8",429,"""Un filme impresionante de principio a fin (.....","""El fervor religioso (...) incluso la épica de...","""La directora lo quiere todo (bien) y todo lo ...","""Amanda Seyfried hace un trabajo excelente en ...","""Resulta difícil no sentir una fascinación int...",NaN,NaN
12,13 mar.,https://www.filmaffinity.com/es/film855002.html,L'inconnu de la Grande Archeaka,2025,105 min.,Francia,Stéphane Demoustier,Stéphane Demoustier. Novela: Laurence Cossé,Claes Bang\nSidse Babett Knudsen\nXavier Dolan...,NaN,...,Año 1983. El nuevo gobierno francés de Françoi...,"6,5",154,"""Una película arquitectónicamente brillante. (...","""El nivel de detalle de Demoustier, lastra el ...","""Lo peor es pensar que es un biopic convencion...","""Solo para expertos y profesionales de la arqu...","""Suspense, humor y un brillante reparto conviv...",,NaN
13,13 mar.,https://www.filmaffinity.com/es/film732131.html,Aimons-nous vivants,2025,90 min.,Francia,Jean-Pierre Améris,"Jean-Pierre Améris, Marion Michau",Valerie Lemercier\nGérard Darmon\nPatrick Tims...,Stéphane Moucha,...,"En un tren a Ginebra, Victoire, una pasajera e...",NaN,NaN,"""Comedia confortable, pero sin mordiente, que ...","""Aunque en la sustancia del argumento está el ...","""Un buen ritmo, unas interpretaciones que enca...",NaN,NaN,NaN,NaN
14,13 mar.,https://www.filmaffinity.com/es/film781408.html,La petite dernière,2025,106 min.,Francia,Hafsia Herzi,Hafsia Herzi. Novela: Fatima Daas,Nadia Melliti\nPark Ji-min\nLouis Memmi\nMouna...,Amin Bouhafa,...,"Fátima, de 17 años, es la pequeña de tres herm...","6,8",188,"""La delicadeza es su principal virtud. Pero no...","""Derrocha rotundidad en su propuesta, arrojo y...","""Una de las virtudes de la película (...) es e...","""El trabajo de Pelliti es portentoso (...) Los...","""El gran descubrimiento de 'La petite dernière...",NaN,NaN
15,13 mar.,https://www.filmaffinity.com/es/film310301.html,Las locas del obelisco,2026,112 min.,España,Pablo Moreno,Pablo Moreno,Paula Iglesias\nJasmina G. Pizarro\nAssumpta S...,Oscar M. Leanizbarrutia,...,"Madrid, finales del siglo XIX. María Ana Allso...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,6 mar.,https://www.filmaffinity.com/es/film316105.html,The Bride!,2026,126 min.,Estados Unidos,Maggie Gyllenhaal,Maggie Gyllenhaal. Personajes: Mary Shelley,Jessie Buckley\nChristian Bale\nPeter Sarsgaar...,Hildur Guðnadóttir,...,"En el Chicago de los años 30, Frankenstein pid...","5,5",1.001,"""Monstruosamente desordenada, monstruosamente ...","""El resultado es decepcionante, sobre todo (y ...","""Sin parecerse apenas a (...) 'La novia de Fra...","""Gritona y prescindible adaptación. (...) una ...","""Cinta irregular, a veces hipnótica, otras dem...",NaN,NaN
17,6 mar.,https://www.filmaffinity.com/es/film150426.html,Hoppers,2026,105 min.,Estados Unidos,Daniel Chong,"Daniel Chong, Jesse Andrews. Historia: Jesse A...",Piper Curda\nVoz\nBobby Moynihan\nVoz\nJon Ham...,Mark Mothersbaugh,...,Mabel es una joven que puede transferir su men...,"7,0",1.882,"""Es una película encantadora, divertida y llen...","""Hay en el filme un humor absurdo de calidad, ...","""Fantasía ecologista modesta y sencilla (...) ...","""Pixar se reinventa con una increíble comedia ...","""Tiene la energía y el encanto para proporcion...",NaN,Pixar (Películas)
18,6 mar.,https://www.filmaffinity.com/es/film923268.html,Le Mage du Kremlinaka,2025,156 min.,Francia,Olivier Assayas,"Emmanuel Carrère, Olivier Assayas. Novela: Giu...",Paul Dano\nAlicia Vikander\nJude Law\nTom Stur...,NaN,...,En medio del caos postsoviético de los años 90...,"6,1",334,"""Una obra imponente (...) Al culminar la rocos...","""Assayas (...) se pierde entre el aluvión de d...","""Un presidente gélido, para una película de hi...","""Aunque larga y discursiva, dibuja con interés...","""Revisa la historia rusa de las últimas década...",,NaN
19,6 mar.,https://www.filmaffinity.com/es/film295464.html,Den Sidste Vikingaka,2025,116 min.,Dinamarca,Anders Thomas Jensen,Anders Thomas Jensen,Mads Mikkelsen\nNikolaj Lie Kaas\nSøren Mallin...,Jeppe Kaas,...,Anker sale de prisión tras cumplir una condena...,"6,9",1.224,"""Con su alocada mezcla de géneros (...) es una...","""Un ejercicio de cine tan exasperante y, por m...","""Toda esa ligereza negra (...) que se solapa c...","""La película habla de la diferencia, de los in...","""Comedia negra negrísima, los Beatles y ABBA t...",,NaN
20,6 mar.,https://www.filmaffinity.com/es/film285634.html,Cleaner,2025,95 min.,Reino Unido,Martin Campbell,"Simon Uttley, Matthew Orton, Paul Andrew Williams",Daisy Ridley\nTaz Skylar\nClive Owen\nRay Fear...,Tom Hodge,...,Un grupo de activistas toma el control de la g...,"4,7",288,"""Daisy Ridley regresa con un Martin Campbell p...","""Una película entretenida (...) Ridley y la pu...","""Aunque puede que 'Cleaner' no sea una de las ...","""Otro mes, otro clon de 'Die Hard' (...) Puntu...","""El director Martin Campbell aporta mano firme...",NaN,NaN
21,6 mar.,https://www.filmaffinity.com/es/film324038.html,Elevation,2024,90 min.,Estados Unidos,George Nolfi,"John Glenn, Jacob Roman, Kenny Ryan",Anthony Mackie\nMorena Baccarin\nMaddie Hasson...,H. Scott Salinas,...,El mundo ha cambiado. El único lugar habitable...,"4,9",472,"""Un trabajo suficiente en lo técnico pero deri...","""Es evidente que aspira a ser algo más que una...","""Es perezosa y poco inspirada, pero si hay alg...","""Está lo suficientemente pulida y emocionante ...","""Aun siendo estándar y floja a veces, 'Elevati...",NaN,NaN
22,6 mar.,https://www.filmaffinity.com/es/film190955.html,Caminando con el diablo,2026,84 min.,España,Rubén Pérez Barrena,"Jesús Miguel Quintana, Rubén Pérez Barrena",Tamar Novas\nMarina Salas\nIván Marcos\nAnnick...,Juanjo Javierre,...,"España, años ochenta. Miguel y Alicia arrastra...","6,4",124,"""Un competente thriller rural (...) Un prólogo...","""Sanguinolento thriller rural en estado casi p...","""Un thriller seco, brutal (...) Cuenta con int...","""La película es entretenida, sí. ¿Es un tanto ...","""En el alambre entre el género y lo genérico, ...",NaN,NaN
23,6 mar.,https://www.filmaffinity.com/es/film363348.html,Pillion,2025,106 min.,Reino Unido,Harry Lighton,Harry Lighton. Libro: Adam Mars-Jones,Alexander Skarsgård\nHarry Melling\nBrian Mart...,Oliver Coates,...,"Colin, un hombre introvertido, se queda prenda...","6,9",1.305,"""Sorprendente (en todos los aspectos) (...) ha...","""Lighton nos recrea con las contradicciones in...","""Lo mejor: La espléndida interpretación de Har...","""Una película genial (...) largometraje a mil ...","""Es una comedia romántica inusual, muy atrevid...",NaN,NaN
24,6 mar.,https://www.filmaffinity.com/es/film633097.html,The Face of the Faceless,2023,136 min.,India,Shaison P Ouseph,Jayapal Anandan,"Vincy Aloshious, Jeett Matharu, Stanley Kozhic...",Alphons Joseph,...,La hermana Rani Maria fue una monja misionera ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,6 mar.,https://www.filmaffinity.com/es/film124261.html,My Father's Shadow,2025,94 min.,Nigeria,Akinola Davies,"Akinola Davies, Wale Davies",Ṣọpẹ́ Dìrísù\nGodwin Egbo\nChibuike Marvelous ...,"Cj Mirra, Duval Timothy",...,"En el transcurso de un solo día en Lagos, la c...","7,2",86,"""Una bella elegía sobre la identidad (...) Con...","""Es uno de los más bellos y emocionantes debut...","""Encuentra su mayor virtud en la manera propia...","""Reúne lo íntimo con lo colectivo y lo polític...","""La película nos introduce con eficacia en la ...",NaN,NaN
26,6 mar.,https://www.filmaffinity.com/es/film703556.html,Karavanaka,2025,103 min.,República Checa,Zuzana Kirchnerová,"Tomas Bojar, Zuzana Kirchnerová, Kristina Majova",Anna Geislerová\nDavid Vostrcil\nJuliana Olhov...,"Aid Kid, Viera Marinová",...,Ester acaba de cumplir 45 años y no tiene nada...,NaN,NaN,"""Marcada por sus verdades emocionales y sus in...","""Una película trepidante de viaje por carreter...","""Aunque técnicamente es impresionante, la pelí...","""Zuzana Kirchnerova ha transformado una histor...","""Introduce temas socialmente sensibles y a men...",,NaN
27,27 feb.,https://www.filmaffinity.com/es/film675046.html,Scream 7,2026,114 min.,Estados Unidos,Kevin Williamson,"Kevin Williamson, Guy Busick. Historia: James ...",Neve Campbell\nIsabel May\nCourteney Cox\nSam ...,Marco Beltrami,...,Cuando un nuevo asesino Ghostface aparece en e...,"5,3",2.091,"""Comienza muy bien y cuenta con un primer terc...","""Scream 7 te da una de cal y otra de arena: ar...","""Ni el genial regreso de Neve Campbell evita l...","""Williamson ha vuelto a lo básico, pero el res...","""Tras un comienzo excesivamente largo, en el q...",NaN,Scream
28,27 feb.,https://www.filmaffinity.com/es/film403747.html,Jean Valjeanaka,2025,98 min.,Francia,Éric Besnard,Éric Besnard. Novela: Victor Hugo,Grégory Gadebois\nBernard Campan\nAlexandra La...,Christophe Julien,...,"1815. Jean Valjean sale del presidio, destroza...","6,4",136,"""Es una obra que busca el detalle en su imagen...","""Se centra en la parte menos visitada de la no...","""Lo más destacable de esta plúmbea historia de...","""Es compleja de explicar, porque desde fuera p...","""La apuesta de Éric Besnard es convertir un re...",,Adaptaciones de Victor Hugo | Los miserables
29,27 feb.,https://www.filmaffinity.com/es/film520114.html,"Sorry, Baby",2025,103 min.,Estados Unidos,Eva Victor,Eva Victor,Eva Victor\nNaomi Ackie\nLucas Hedges\nJohn Ca...,Rob Rusli,...,Una joven atraviesa un momento vital marcado p...,"6,6",1.189,"""Eva Victor, directora, guionista y actriz de ...","""Eva Victor completa uno de los más sorprenden...","""Una ópera prima delicada y punzante (...) Es ...","""Nada resuelve, y acaso ahí radique el enorme ...","""Un debut original y prometedor (...) Puntuaci...",NaN,NaN
30,27 feb.,https://www.filmaffinity.com/es/film630582.html,EPiC: Elvis Presley in Concert,2025,90 min.,Australia,Baz Luhrmann,NaN,Elvis Presley,Elliott Wheeler,...,"La figura del gran Elvis Presley, con imágenes...","7,8",301,"""La estrella del rock, en vivo y casi en direc...","""Una película que demuestra que Elvis sigue má...","""Es cierto, Elvis sigue vivo (...) A quien le ...","""Una gloriosa catarsis y resurrección del rey ...","""Una delicia para cualquier fan de Elvis"" \nMo...",NaN,NaN
31,27 feb.,https://www.filmaffinity.com/es/film327123.html,Orwell: 2+2=5,2025,119 min.,Francia,Raoul Peck,NaN,Documental,Alexei Aigui,...,1949. George Orwell termina la que será su últ...,"6,6",263,"""No me distraigo en ningún momento del atracti...","""Con una contundencia que por momentos roza el...","""Su control [de Peck] sobre las posibilidades ...","""Una película que, a pesar de ser unidireccion...","""Las preguntas están ahí (...) Tan sólo por es...",NaN,NaN
32,20 feb.,https://www.filmaffinity.com/es/film853860.html,Greenland 2: Migration,2026,98 min.,Estados Unidos,Ric Roman Waugh,"Chris Sparling, Mitchell LaFortune",Gerard Butler\nMorena Baccarin\nRoman Griffin ...,David Buckley,...,Después de sobrevivir al fin del mundo por la ...,"4,5",976,"""No [es] para tirar cohetes (...) El viaje est...","""Más allá de (...) espectáculo de ideología ra...","""Una película entretenida, eficaz y funcional ...","""Un cine honesto que no abunda. (...) Su modes...","""Esta secuela carece de toda lógica y propone ...",NaN,NaN
33,20 feb.,https://www.filmaffinity.com/es/film457500.html,O Agente Secretoaka,2025,158 min.,Brasil,Kleber Mendonça Filho,Kleber Mendonça Filho,Wagner Moura\nAlice Carvalho\nGabriel Leone\nU...,"Mateus Alves, Tomaz Alves de Souza",...,"En 1977, durante la dictadura militar brasileñ...","6,8",4.550,"""Magnífica (...) Resulta vibrante (por su ritm...","""Kleber Mendonça Filho acierta con un retrato ...","""Un thriller lleno de colorido, intención y ci...","""No hay nada en la concienciada película que m...","""Arrebatador cóctel de intriga, política y cin...",,NaN
34,20 feb.,https://www.filmaffinity.com/es/film870836.html,Shelby Oaks,2024,99 min.,Estados Unidos,Chris Stuckmann,"Chris Stuckmann. Historia: Sam Liz, Chris Stuc...",Camille Sullivan\nSarah Durn\nBrendan Sexton I...,Aaron J. Morton,...,Cuando un documentalista descubre una nueva pi...,"5,4",693,"""Un film de terror sin ambages, una sombría tr...","""Crea situaciones de tensión espeluznantes (.....","""Chris Stuckmann reboza el 'true crime' en ter...","""Stuckmann es sin duda el periodista reconvert...","""Es un batiburrillo aburrido y poco original q...",NaN,NaN
35,20 feb.,https://www.filmaffinity.com/es/film210175.html,Amélie et la Métaphysique des tubesaka,2025,77 min.,Francia,"Mailys Vallade, Liane-Cho Han Jin Kuang","Liane-Cho Han Jin Kuang, Eddine Noël, Aude Py,...",Animación,Mari Fukuhara,...,"Hasta los dos años y medio, Amélie se describí...","7,3",840,"""No queda otra que rendirse a la imaginación, ...","""Bonita aproximación a la más temprana infanci...","""Un filme de animación muy delicado y preciso ...","""Es un festival del color, que se beneficia de...","""Maravilla animada (...) con un estilo entre b...",,NaN
36,20 feb.,https://www.filmaffinity.com/es/film134886.html,"Balandrau, vent salvatge",2026,116 min.,España,Fernando Trullols,Danielle Schleif. Novela: Jordi Cruz,Álvaro Cervantes\nBruna Cusí\nMarc Martínez\nE...,Música original: Arnau Bataller,...,"El 30 de diciembre del 2000, un grupo de amigo...","6,9",581,"""Un filme de difícil y complicado rodaje así c...","""En 'Balandrau' la tragedia se vive en primero...","""Unos veinte minutos finales excelentes. Es há...","""Se ve el firme pulso [de Trullols] para las e...",NaN,NaN,NaN

Probamos la función que hemos hecho. Aquí tienes un enlace de prueba: https://www.filmaffinity.com/es/film599984.html

In [8]:
prueba = get_datos_pelicula(driver, "https://www.filmaffinity.com/es/film618375.html", "fecha")
prueba

{'fecha_estreno': 'fecha',
 'url': 'https://www.filmaffinity.com/es/film618375.html',
 'Título original': 'Oblivion',
 'Año': '2013',
 'Duración': '126 min.',
 'País': ' Estados Unidos',
 'Dirección': 'Joseph Kosinski',
 'Guion': 'Joseph Kosinski, Michael Arndt, Karl Gajdusek. Cómic: Joseph Kosinski, Arvid Nelson',
 'Reparto': 'Tom Cruise\nAndrea Riseborough\nOlga Kurylenko\nMorgan Freeman\nNikolaj Coster-Waldau\nZoe Bell',
 'Música': 'Anthony Gonzalez, M83, Joseph Trapanese',
 'Fotografía': 'Claudio Miranda',
 'Compañías': 'Universal Pictures, Chernin Entertainment, Relativity Studios, Monolith Pictures, Radical Studios',
 'Género': 'Ciencia ficción. Intriga | Futuro postapocalíptico. Distopía. Cómic',
 'Sinopsis': 'Año 2073. Hace más de 60 años la Tierra fue atacada; se ganó la guerra, pero la mitad del planeta quedó destruido, y todos los seres humanos fueron evacuados. Jack Harper (Tom Cruise), un antiguo marine, es uno de los últimos hombres que la habitan. Es un ingeniero de Drones que participa en una operación para extraer los recursos vitales del planeta. Su misión consiste en patrullar diariamente los cielos. Un día, rescata a una desconocida de una nave espacial y, entonces, se ve obligado a replantearse sus convicciones más profundas. (FILMAFFINITY)',
 'nota_media': '5,8',
 'cantidad_votos': '48.205',
 'critica_0': '"Un nuevo ejercicio de artillería pesada para arrasar taquillas, sin renunciar a una cierta mirada adulta y a una cierta ambición creativa. (...) La marca Cruise da lo que uno espera -es entretenimiento sólido y generoso-, pero ni un aliciente más" \nJordi Costa: Diario El País',
 'critica_1': '"Un pastiche cuya única virtud corre a cuenta del departamento de los efectos visuales. (...) una historia incapaz de tomar la suficiente distancia con lo narrado para resultar inteligente" \nLuis Martínez: Diario El Mundo',
 'critica_2': '"No se queda sólo en una peripecia llena de aventura, acción y entretenido espejismo (...), sino que engarza entre todo ello una idea, una fábula, entre la realidad y su manipulación (...) Puntuación: ★★★ (sobre 5)"\nOti Rodríguez Marchante: Diario ABC',
 'critica_3': '"El «patchwork» de diseño que combina ideas visuales de «2001» y «Alien» es fantástico, espectacular (...) También es moroso, tedioso, lacónico. (...) a la película le cuesta aceptar su dimensión existencialista: su mensaje es demasiado benévolo" \nSergi Sánchez: Diario La Razón',
 'critica_4': '"Sus mayores virtudes se hallan en lo estético (...) Una historia con muchas posibilidades arruinada por un tratamiento demasiado solemne. (...) Puntuación: ★★½ (sobre 5)" \nYago García: Cinemanía'}

Entramos en el link de las películas en cartelera

In [ ]:
# tu código

In [ ]:
# tu código

[<undetected_chromedriver.webelement.WebElement (session="88d13dc2b36b434bc6ba970c4da8d75a", element="f.1B45C29A1E40EB3D37BD0DBD2F1F28D6.d.3297110C6BC4EC58CCD60B4D9B7DB636.e.7913")>,
 <undetected_chromedriver.webelement.WebElement (session="88d13dc2b36b434bc6ba970c4da8d75a", element="f.1B45C29A1E40EB3D37BD0DBD2F1F28D6.d.3297110C6BC4EC58CCD60B4D9B7DB636.e.9469")>,
 <undetected_chromedriver.webelement.WebElement (session="88d13dc2b36b434bc6ba970c4da8d75a", element="f.1B45C29A1E40EB3D37BD0DBD2F1F28D6.d.3297110C6BC4EC58CCD60B4D9B7DB636.e.9492")>,
 <undetected_chromedriver.webelement.WebElement (session="88d13dc2b36b434bc6ba970c4da8d75a", element="f.1B45C29A1E40EB3D37BD0DBD2F1F28D6.d.3297110C6BC4EC58CCD60B4D9B7DB636.e.9507")>,
 <undetected_chromedriver.webelement.WebElement (session="88d13dc2b36b434bc6ba970c4da8d75a", element="f.1B45C29A1E40EB3D37BD0DBD2F1F28D6.d.3297110C6BC4EC58CCD60B4D9B7DB636.e.9528")>]

Sacamos todas las películas y llamamos a la función con cada película

In [ ]:
# tu código

In [43]:
links

[{'título': 'Dhurandhar: The Revenge ',
  'url': 'https://www.filmaffinity.com/es/film343952.html',
  'estreno': '19 mar.'},
 {'título': 'Torrente presidente ',
  'url': 'https://www.filmaffinity.com/es/film453739.html',
  'estreno': '13 mar.'},
 {'título': 'Águilas de El Cairo ',
  'url': 'https://www.filmaffinity.com/es/film314137.html',
  'estreno': '13 mar.'},
 {'título': 'El testamento de Ann Lee ',
  'url': 'https://www.filmaffinity.com/es/film842010.html',
  'estreno': '13 mar.'},
 {'título': 'El arquitecto ',
  'url': 'https://www.filmaffinity.com/es/film855002.html',
  'estreno': '13 mar.'},
 {'título': 'No te queda otra ',
  'url': 'https://www.filmaffinity.com/es/film732131.html',
  'estreno': '13 mar.'},
 {'título': 'La hija pequeña ',
  'url': 'https://www.filmaffinity.com/es/film781408.html',
  'estreno': '13 mar.'},
 {'título': 'Las locas del obelisco ',
  'url': 'https://www.filmaffinity.com/es/film310301.html',
  'estreno': '13 mar.'},
 {'título': '¡La novia! ',
  'url': 'https://www.filmaffinity.com/es/film316105.html',
  'estreno': '6 mar.'},
 {'título': 'Hoppers ',
  'url': 'https://www.filmaffinity.com/es/film150426.html',
  'estreno': '6 mar.'},
 {'título': 'El mago del Kremlin ',
  'url': 'https://www.filmaffinity.com/es/film923268.html',
  'estreno': '6 mar.'},
 {'título': 'El último vikingo ',
  'url': 'https://www.filmaffinity.com/es/film295464.html',
  'estreno': '6 mar.'},
 {'título': 'Cleaner: Rescate vertical ',
  'url': 'https://www.filmaffinity.com/es/film285634.html',
  'estreno': '6 mar.'},
 {'título': 'Línea de extinción ',
  'url': 'https://www.filmaffinity.com/es/film324038.html',
  'estreno': '6 mar.'},
 {'título': 'Caminando con el diablo ',
  'url': 'https://www.filmaffinity.com/es/film190955.html',
  'estreno': '6 mar.'},
 {'título': 'Pillion ',
  'url': 'https://www.filmaffinity.com/es/film363348.html',
  'estreno': '6 mar.'},
 {'título': 'Aves de corral ',
  'url': 'https://www.filmaffinity.com/es/film898988.html',
  'estreno': '6 mar.'},
 {'título': 'A Magnificent Life ',
  'url': 'https://www.filmaffinity.com/es/film588486.html',
  'estreno': '6 mar.'},
 {'título': 'América Hispana. El legado de las olas ',
  'url': 'https://www.filmaffinity.com/es/film761280.html',
  'estreno': '6 mar.'},
 {'título': 'El rostro del perdón ',
  'url': 'https://www.filmaffinity.com/es/film633097.html',
  'estreno': '6 mar.'},
 {'título': 'La sombra de mi padre ',
  'url': 'https://www.filmaffinity.com/es/film124261.html',
  'estreno': '6 mar.'},
 {'título': 'Caravan ',
  'url': 'https://www.filmaffinity.com/es/film703556.html',
  'estreno': '6 mar.'},
 {'título': 'Scream 7 ',
  'url': 'https://www.filmaffinity.com/es/film675046.html',
  'estreno': '27 feb.'},
 {'título': 'Scarlet ',
  'url': 'https://www.filmaffinity.com/es/film792007.html',
  'estreno': '27 feb.'},
 {'título': 'Los miserables. El origen ',
  'url': 'https://www.filmaffinity.com/es/film403747.html',
  'estreno': '27 feb.'},
 {'título': 'Sorry, Baby ',
  'url': 'https://www.filmaffinity.com/es/film520114.html',
  'estreno': '27 feb.'},
 {'título': 'EPiC: Elvis Presley in Concert ',
  'url': 'https://www.filmaffinity.com/es/film630582.html',
  'estreno': '27 feb.'},
 {'título': 'La residencIA ',
  'url': 'https://www.filmaffinity.com/es/film704018.html',
  'estreno': '27 feb.'},
 {'título': 'Iron Lung: Océano de sangre ',
  'url': 'https://www.filmaffinity.com/es/film227396.html',
  'estreno': '27 feb.'},
 {'título': 'Orwell: 2+2=5 ',
  'url': 'https://www.filmaffinity.com/es/film327123.html',
  'estreno': '27 feb.'},
 {'título': 'Islas ',
  'url': 'https://www.filmaffinity.com/es/film502320.html',
  'estreno': '27 feb.'},
 {'título': 'Hasta la montaña ',
  'url': 'https://www.filmaffinity.com/es/film504352.html',
  'estreno': '27 feb.'},
 {'título': 'Manas ',
  'url': 'https://www.filmaffinity.com/es/film486759.html',
  'estreno': '27 feb.'},
 {'título': 'Greenland 2 ',
  'url': 'https://www.filmaffinity.com/es/film853860.html',
  'estreno': '20 feb.'},
 {'título': 'El agente secreto ',
  'url': 'https://www.filmaffinity.com/es/film457500.html',
  'estreno': '20 feb.'},
 {'título': 'El fantasma de mi mujer ',
  'url': 'https://www.filmaffinity.com/es/film691627.html',
  'estreno': '20 feb.'},
 {'título': 'La maldición de Shelby Oaks ',
  'url': 'https://www.filmaffinity.com/es/film870836.html',
  'estreno': '20 feb.'},
 {'título': 'Little Amélie ',
  'url': 'https://www.filmaffinity.com/es/film210175.html',
  'estreno': '20 feb.'},
 {'título': 'Balandrau, viento salvaje ',
  'url': 'https://www.filmaffinity.com/es/film134886.html',
  'estreno': '20 feb.'},
 {'título': 'Las líneas discontinuas ',
  'url': 'https://www.filmaffinity.com/es/film409255.html',
  'estreno': '20 feb.'},
 {'título': 'Cumbres borrascosas ',
  'url': 'https://www.filmaffinity.com/es/film608251.html',
  'estreno': '13 feb.'},
 {'título': 'Como cabras ',
  'url': 'https://www.filmaffinity.com/es/film967461.html',
  'estreno': '13 feb.'},
 {'título': 'Ruta de escape ',
  'url': 'https://www.filmaffinity.com/es/film960118.html',
  'estreno': '13 feb.'},
 {'título': 'Castigo divino ',
  'url': 'https://www.filmaffinity.com/es/film226633.html',
  'estreno': '13 feb.'},
 {'título': 'El vestido ',
  'url': 'https://www.filmaffinity.com/es/film559268.html',
  'estreno': '13 feb.'},
 {'título': 'No hay otra opción ',
  'url': 'https://www.filmaffinity.com/es/film288774.html',
  'estreno': '13 feb.'},
 {'título': 'La fiera ',
  'url': 'https://www.filmaffinity.com/es/film571051.html',
  'estreno': '6 feb.'},
 {'título': 'Tres adioses ',
  'url': 'https://www.filmaffinity.com/es/film580752.html',
  'estreno': '6 feb.'},
 {'título': 'Evolution ',
  'url': 'https://www.filmaffinity.com/es/film872994.html',
  'estreno': '6 feb.'},
 {'título': 'La tarta del presidente ',
  'url': 'https://www.filmaffinity.com/es/film888907.html',
  'estreno': '6 feb.'},
 {'título': 'Marty Supreme ',
  'url': 'https://www.filmaffinity.com/es/film380589.html',
  'estreno': '30 ene.'},
 {'título': 'Aída y vuelta ',
  'url': 'https://www.filmaffinity.com/es/film186074.html',
  'estreno': '30 ene.'},
 {'título': 'La chica zurda ',
  'url': 'https://www.filmaffinity.com/es/film730574.html',
  'estreno': '30 ene.'},
 {'título': 'Hamnet ',
  'url': 'https://www.filmaffinity.com/es/film868058.html',
  'estreno': '23 ene.'},
 {'título': 'Ídolos ',
  'url': 'https://www.filmaffinity.com/es/film510990.html',
  'estreno': '23 ene.'},
 {'título': 'Rental Family (Familia de alquiler) ',
  'url': 'https://www.filmaffinity.com/es/film442925.html',
  'estreno': '9 ene.'},
 {'título': 'La asistenta ',
  'url': 'https://www.filmaffinity.com/es/film530880.html',
  'estreno': '1 ene.'},
 {'título': 'Rondallas ',
  'url': 'https://www.filmaffinity.com/es/film683814.html',
  'estreno': '1 ene.'},
 {'título': 'Abuela tremenda ',
  'url': 'https://www.filmaffinity.com/es/film515832.html',
  'estreno': '1 ene.'},
 {'título': 'Avatar: Fuego y ceniza ',
  'url': 'https://www.filmaffinity.com/es/film191071.html',
  'estreno': '19 dic.'},
 {'título': 'Valor sentimental ',
  'url': 'https://www.filmaffinity.com/es/film901036.html',
  'estreno': '5 dic.'},
 {'título': 'Zootrópolis 2 ',
  'url': 'https://www.filmaffinity.com/es/film269061.html',
  'estreno': '28 nov.'},
 {'título': 'Núremberg ',
  'url': 'https://www.filmaffinity.com/es/film597108.html',
  'estreno': '28 nov.'},
 {'título': 'Bugonia ',
  'url': 'https://www.filmaffinity.com/es/film964057.html',
  'estreno': '7 nov.'},
 {'título': 'Los domingos ',
  'url': 'https://www.filmaffinity.com/es/film584300.html',
  'estreno': '24 oct.'},
 {'título': 'Sirât ',
  'url': 'https://www.filmaffinity.com/es/film780154.html',
  'estreno': '6 jun.'},
 {'título': 'Los pecadores ',
  'url': 'https://www.filmaffinity.com/es/film699169.html',
  'estreno': '16 abr.'},
 {'título': 'Una batalla tras otra ',
  'url': 'https://www.filmaffinity.com/es/film910030.html',
  'estreno': '26 sept.'},
 {'título': 'F1: La película ',
  'url': 'https://www.filmaffinity.com/es/film935703.html',
  'estreno': '27 jun.'}]

Ahora usamos los links para llamar a la funcion y sacar los datos

In [ ]:
# tu código

Añadida Dhurandhar: The Revengeaka
Añadida Torrente presidenteaka
Añadida Eagles of the Republicaka
Añadida The Testament of Ann Lee
Añadida L'inconnu de la Grande Archeaka
Añadida Aimons-nous vivants
Añadida La petite dernière
Añadida Las locas del obelisco
Añadida The Bride!
Añadida Hoppers
Añadida Le Mage du Kremlinaka
Añadida Den Sidste Vikingaka
Añadida Cleaner
Añadida Elevation
Añadida Caminando con el diablo
Añadida Pillion
Añadida Aves de corral
Añadida Marcel et Monsieur Pagnolaka
Añadida América Hispana. El legado de las olas
Añadida The Face of the Faceless
Añadida My Father's Shadow
Añadida Karavanaka
Añadida Scream 7
Añadida Scarletaka
Añadida Jean Valjeanaka
Añadida Sorry, Baby
Añadida EPiC: Elvis Presley in Concert
Añadida Dalloway
Añadida Iron Lung
Añadida Orwell: 2+2=5
Añadida Islas
Añadida Bergersaka
Añadida Manas
Añadida Greenland 2: Migration
Añadida O Agente Secretoaka
Añadida El fantasma de mi mujer
Añadida Shelby Oaks
Añadida Amélie et la Métaphysique des tubesaka
Añadida Balandrau, vent salvatge
Añadida As liñas descontinuas
Añadida Wuthering Heightsaka
Añadida GOAT
Añadida Crime 101
Añadida Castigo divino
Añadida El vestidoaka
Añadida No Other Choiceaka
Añadida La fiera
Añadida Tre ciotole
Añadida Evolution
Añadida Mamlaket Al-Qasabaka
Añadida Marty Supremeaka
Añadida Aída y vuelta
Añadida Left-Handed Girl
Añadida Hamnet
Añadida Ídolos
Añadida Rental Family
Añadida The Housemaid
Añadida Rondallas
Añadida Abuela tremenda
Añadida Avatar: Fire and Ash
Añadida Sentimental Valueaka
Añadida Zootopia 2
Añadida Nuremberg
Añadida Bugonia
Añadida Los domingos
Añadida Sirât
Añadida Sinners
Añadida One Battle After Another
Añadida F1: The Movie

In [45]:
df

,fecha_estreno,url,Título original,,Año,Duración,País,Dirección,Guion,Reparto,...,Género,Sinopsis,Grupos,nota_media,cantidad_votos,critica_0,critica_1,critica_2,critica_3,critica_4
0,19 mar.,https://www.filmaffinity.com/es/film343952.html,Dhurandhar: The Revengeaka,,2026,210 min.,India,Aditya Dhar,Aditya Dhar,Ranveer Singh\nSanjay Dutt\nAkshaye Khanna\nMa...,...,Acción. Thriller | Secuela. Espionaje,"Bajo la identidad de Hamza Ali Mazari, el espí...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13 mar.,https://www.filmaffinity.com/es/film453739.html,Torrente presidenteaka,,2026,102 min.,España,Santiago Segura,Santiago Segura,Santiago Segura\nGabino Diego\nRamón Langa\nCa...,...,Comedia | Comedia negra. Sátira. Política. Sec...,"José Luis Torrente, siempre convencido de ser ...",Torrente,"5,9",3.144,"""Una sátira tan ocurrente y divertida como opo...","""Soez, excesiva y por momentos muy divertida. ...","""Cuñadismo para todos los públicos (...) No ha...","""Una comedia facilona (...) sin tanto colmillo...","""Es fiel a la saga, pero va un poco más allá (..."
2,13 mar.,https://www.filmaffinity.com/es/film314137.html,Eagles of the Republicaka,,2025,127 min.,Suecia,Tarik Saleh,Tarik Saleh,Fares Fares\nLyna Khoudri\nZineb Triki\nAmr Wa...,...,Thriller. Drama | Cine dentro del cine. Política,George Fahmy (Fares Fares) el actor más querid...,Trilogía de El Cairo,"6,4",169,"""Cierra la trilogía de Tarik Saleh sobre la ci...","""En su núcleo central deambula un tanto entre ...","""De sus imágenes emerge un duro retrato crític...","""El argumento que trata es interesante, tiene ...","""Se ve lastrada por la tosquedad como narrador..."
3,13 mar.,https://www.filmaffinity.com/es/film842010.html,The Testament of Ann Lee,NaN,2025,136 min.,Reino Unido,Mona Fastvold,"Mona Fastvold, Brady Corbet",Amanda Seyfried\nThomasin McKenzie\nLewis Pull...,...,Drama. Musical | Basado en hechos reales. Sigl...,"Inspirada en hechos reales, se centra en la lí...",NaN,"5,9",345,"""Un filme impresionante de principio a fin (.....","""El fervor religioso (...) incluso la épica de...","""La directora lo quiere todo (bien) y todo lo ...","""Amanda Seyfried hace un trabajo excelente en ...","""Resulta difícil no sentir una fascinación int..."
4,13 mar.,https://www.filmaffinity.com/es/film855002.html,L'inconnu de la Grande Archeaka,,2025,105 min.,Francia,Stéphane Demoustier,Stéphane Demoustier. Novela: Laurence Cossé,Claes Bang\nSidse Babett Knudsen\nXavier Dolan...,...,Drama | Basado en hechos reales. Biográfico. A...,Año 1983. El nuevo gobierno francés de Françoi...,NaN,"6,4",130,"""Una película arquitectónicamente brillante. (...","""El nivel de detalle de Demoustier, lastra el ...","""Lo peor es pensar que es un biopic convencion...","""Solo para expertos y profesionales de la arqu...","""Suspense, humor y un brillante reparto conviv..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,24 oct.,https://www.filmaffinity.com/es/film584300.html,Los domingos,NaN,2025,110 min.,España,Alauda Ruiz de Azúa,Alauda Ruiz de Azúa,Blanca Soroa\nPatricia López Arnaiz\nMiguel Ga...,...,Drama | Religión. Familia. Monjas. Adolescencia,"Ainara (Blanca Soroa), una joven idealista y b...",NaN,"7,3",17.841,"""La nueva propuesta de la directora (...), fie...","""Ruiz de Azúa infunde fe en el gran cine (...)...","""Una película tan a contrapelo y tan luminosa,...","""Hay que celebrar el rigor cartesiano, equilib...","""Confirma que Ruiz de Azúa es una directora de..."
65,6 jun.,https://www.filmaffinity.com/es/film780154.html,Sirât,NaN,2025,114 min.,España,Oliver Laxe,"Oliver Laxe, Santiago Fillol",Sergi López\nBruno Núñez\nJade Oukid\nStefania...,...,Drama. Intriga. Thriller | Road Movie. Secuest...,Un hombre (Sergi López) y su hijo (Bruno Núñez...,NaN,"6,2",25.289,"""Laxe revienta Cannes con el trágico y brutal ...","""Una propuesta tan radical y honda como sorpre...","""Brillante ejercicio de hipnosis (...) una obr...","""Durante todo el metraje estoy dentro de esta ...","""“Sirât” es una película áspera pero hipnótica..."
66,16 abr.,https://www.filmaffinity.com/es/film699169.html,Sinners,NaN,2025,137 min.,Estados Unidos,Ryan Coogler,Ryan Coogler,Michael B. Jordan\nHailee Steinfeld\nMiles Cat...,...,Terror. Thriller | Música. Drama sureño. Años ...,Tratando de dejar atrás sus problemáticas aunq...,NaN,"6,5",26.907,"""Magnífica (...) Es muy atractiva por su suger...","""Imprevisible y grandiosa película de terror -...","""Festín para los amantes del terror y de 'El c...","""Propuesta original en su posmodernismo, disfr...","""Compleja, intrincada e irregular (...) tiene ..."
67,26 sept.,https://www.filmaffinity.com/es/film910030.html,One Battle After Another,NaN,2025,161 min.,Estados Unidos,Paul Thomas Anderson,Paul Thomas Anderson. Novela: Thomas Pynchon,Leonardo DiCaprio\nSean Penn\nChase Infiniti\n...,...,Thriller. Acción. Drama. Comedia | Inmigración...,"Un ex revolucionario, tras años apartado de la...",NaN,"7,0",30.130,"""Un enfebrecido viaje al fondo de la concienci...","""La película más divertida, furiosa y visceral...","""Un bostezo tras otro (...) una de las películ...","""Extraordinaria (...) obra maestra inabarcable...","""Va de un lado a otro todo el rato y no para d..."
68,27 jun.,https://www.filmaffinity.com/es/film935703.html,F1: The Movie,NaN,2025,155 min.,Estados Unidos,Joseph Kosinski,"Ehren Kruger. Historia: Joseph Kosinski, Ehren...",Brad Pitt\nDamson Idris\nKerry Condon\nJavier ...,...,Acción. Drama | F1. Coches / Automovilismo,Sonny Hayes fue el fenómeno más prometedor de ...,NaN,"6,8",17.674,"""Kosinski lleva la fórmula Top Gun a la Fórmul...","""Muestra una dedicación absoluta a la transmis...","""No logro apasionarme en ningún momento (...) ...","""Que nos adelanten por la derecha si este no e...","""Si le encanta la velocidad, (...) si le pirra..."